version: 2
jobs:
  build:
    working_directory: ~/Saivo-Android
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Add Gradle Properties
          command: 'printf "android.useAndroidX=true\n
          android.enableJetifier=true\nkotlin.code.style=official\n" >> gradle.properties &&
          printf "MAP_KEY=\"\"\nAPI_HOST=\"\"\nACCESS_TOKEN=\"\"\n" >> gradle.properties'
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results