package com.saivo.recommendo.util.helpers


const val DEVICE_ID = 0
const val TOKEN_ID = DEVICE_ID
const val CLIENT_ID = DEVICE_ID
const val LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL"
const val LOGIN_UNSUCCESSFUL = "LOGIN_UNSUCCESSFUL"
const val REGISTRATION_SUCCESSFUL = "REGISTRATION_SUCCESSFUL"
const val REQUEST_DIALOG_ON_ERROR = 4393
const val REQUEST_DEVICE_GPS_PERMISSION = 4350
const val REQUEST_FINE_LOCATION_PERMISSION = 4590
